name: Telegram Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # Каждые 2 часа

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run bot
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
        run: python bot.py
